### ISSUE TITLE
Problem with dynamic imports

### ISSUE THREAD

**Issue by ilionic** [nexdrew/next-build-id#1]
When using dynamic imports i.e.

```
import dynamic from 'next/dynamic';

const MyModule = dynamic(import('./my-module'), {
  ssr: false,
  loading: () => <span />,
});
```

Getting bunch of errors:
```
app.js:1 Uncaught (in promise) Error: Loading chunk 3 failed.
```
So all chunks are still referencing previous build id

**Comment by ilionic** [comment]
Ok, possibly related https://github.com/zeit/next.js/issues/3446

**Comment by nexdrew** [comment]
Hi 👋 thanks for reporting!

What can `next-build-id` do to help with this problem? Are there additional files in the `.next` output directory that we should be looking for/updating?

From my local testing, it _does_ look like the BUILD_ID value ends up in some hardcoded paths like `p="/_next/22d7f2fe-f43e-43fb-9f90-41633d0f92b3/webpack/"` in app.js and manifest.js. Should `next-build-id` do a global search and replace to better handle these?

**Comment by ilionic** [comment]
hey, global search and replace sounds like sensible option in this case. thanks

**Comment by nexdrew** [comment]
Now that Next.js 6 supports a way to customize the BUILD_ID via next.config.js, I recommend upgrading `next-build-id` to version 2 and using it this way:

```js
// next.config.js
const nextBuildId = require('next-build-id')
module.exports = {
  generateBuildId: async () => {
    const fromGit = await nextBuildId({ dir: __dirname })
    return fromGit.id
  }
}
```

This will set the BUILD_ID to the output of `git rev-parse HEAD` just from running `next build` as normal, so there's no longer a need to run the `next-build-id` CLI after the fact to overwrite the default BUILD_ID.

Now that we can customize the BUILD_ID without a hack, which means the correct id should be used internally by Next.js and apply it everywhere it should be used, I'm going to close this issue. If you upgrade and still have an issue, please report back and we can investigate further. Thanks!
