### ISSUE TITLE
Build Error Occurred

### ISSUE THREAD

**Issue by scefali** [nexdrew/next-build-id#29]
Firstly, I want to thank you immensely for creating this package. I am hoping to use it for a legit Sentry-NextJS integration by using this to set the release as the commit hash. However, I am having some problems getting this work in my latest build:

```
> Build error occurred
19:23:37.663  
Error: Command failed: git --git-dir=/vercel/32bafab9/.git --work-tree=/vercel/32bafab9 rev-parse HEAD
19:23:37.663  
fatal: not a git repository: '/vercel/32bafab9/.git'
19:23:37.663  
    at ChildProcess.exithandler (child_process.js:295:12)
19:23:37.663  
    at ChildProcess.emit (events.js:223:5)
19:23:37.663  
    at maybeClose (internal/child_process.js:1021:16)
19:23:37.663  
    at Socket.<anonymous> (internal/child_process.js:430:11)
19:23:37.663  
    at Socket.emit (events.js:223:5)
19:23:37.663  
    at Pipe.<anonymous> (net.js:664:12) 
```

Here is my `next.config.js` file: https://github.com/scefali/vercel-integration/blob/bac517b6701d382467e7a0be1e8c619d6cb285bf/next.config.js

Let me know if you need any more information.

EDIT: Found a workaround to this using the environment variables described here: https://vercel.com/docs/v2/build-step#system-environment-variables

Just used `VERCEL_GITHUB_COMMIT_SHA`

**Comment by nexdrew** [comment]
The error tells us that the remote directory where you're building is not an actual git repository, meaning the repository metadata (e.g. commit history) is not available, so `next-build-id` won't be able to read the latest commit sha or tag. Apparently, what gets pushed to Vercel is not a full git clone but is probably just a copy of directories/files for the current version of a particular branch.

As you discovered, you can probably just rely on the environment variables provided by Vercel without needing to use `next-build-id` at all.

If you're using the Vercel env vars, you might want to support GitLab and Bitbucket users (as well as GitHub users) by looking at `VERCEL_GITLAB_COMMIT_SHA ` and `VERCEL_BITBUCKET_COMMIT_SHA ` too:

```js
release: process.env.VERCEL_GITHUB_COMMIT_SHA || process.env.VERCEL_GITLAB_COMMIT_SHA || process.env.VERCEL_BITBUCKET_COMMIT_SHA
```

I'm not sure why Vercel doesn't use the same env var for all of them, but there you go.

Good luck with your integration project!

**Comment by scefali** [comment]
> If you're using the Vercel env vars, you might want to support GitLab and Bitbucket users (as well as GitHub users) by looking at VERCEL_GITLAB_COMMIT_SHA and VERCEL_BITBUCKET_COMMIT_SHA too:

Yes, that's the plan. Good callout. Thanks for your help!
