### ISSUE TITLE
Heroku build failures

### ISSUE THREAD

**Issue by sojungko** [nexdrew/next-build-id#9]
Tried the `next build && next-build-id` but get the following error when trying to deploy on Heroku:

```Unexpected error: { Error: Command failed: git --git-dir=/tmp/build_b1a2400958a54ea0fb28e8b3ecb17d71/.git --work-tree=/tmp/build_b1a2400958a54ea0fb28e8b3ecb17d71 rev-parse HEAD
fatal: Not a git repository: '/tmp/build_b1a2400958a54ea0fb28e8b3ecb17d71/.git'
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git --git-dir=/tmp/build_b1a2400958a54ea0fb28e8b3ecb17d71/.git --work-tree=/tmp/build_b1a2400958a54ea0fb28e8b3ecb17d71 rev-parse HEAD' }
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:next" exited with 1.
```
It works fine locally, however. My guess is that because we don't push our `.git` folder to production, Heroku is failing to recognize our git history. Any suggestion on how to bypass this issue?

**Comment by nexdrew** [comment]
Hello 👋

I'm not sure how Heroku clones/handles git repositories, but without a `.git` directory (which would be generated from a `git clone` command), `next-build-id` won't be able to use `git rev-parse HEAD` to determine the latest commit id.

We need to determine if the `.git` directory is really not there or if `next-build-id` is just looking in the wrong place. It looks like your `build:next` yarn task is running in a tmp build directory. Do you know where that's coming from, i.e. defined by Heroku or defined by your app/script?

It might not really matter, but which version of `next` and `next-build-id` are you using? Version 2.0.1 of `next-build-id` will look for a `.git` directory in parent directories as well. And if you're using Next.js 6+, you can use `next-build-id` as a module within a next.config.js file instead of having to use the CLI.

Do you have a public sample project I could test with?

It looks like there's a MD5 hash in the tmp build directory name, do you know where that's coming from? If that were a reliable/consistent hash value, you could potentially use it instead of the git commit id.

**Comment by nexdrew** [comment]
@sojungko Hi, have you had a chance to look into this any further? Are you able to provide answers to any of my questions above?

I plan on test-deploying a sample Next.js app to Heroku to try and reproduce the problem, but I don't know when I'll have the time to do that.

Please let me know if you find anything or have any more info. Thanks!

**Comment by sojungko** [comment]
Hi @nexdrew, thanks for your prompt response! So indeed, `.git` folder does not get pushed to Heroku since it lives in our `.gitignore` file, so we came up with a workaround:

We're gonna try to create a git commit or push hook that would grab the latest git commit hash and inject it into `next.config.js` (not exactly sure how we'll accomplish this, but some variation of this idea should work). Will report back if there's any success!

Oh also, unfortunately the tmp build folder hash was not consistent enough to be used as a build id. I thought that was coming from next build process, but maybe not?

**Comment by sojungko** [comment]
So here's the solution I came up with. I upgraded to next.js 6.0.3^ (upgraded babel to 7 accordingly) and added this to my `next.config.js`:

```js
// next.config.js
const fs = require('fs')
const cp = require('child_process')

module.exports = {
  generateBuildId: () => {
    if (!fs.existsSync('git-commit-hash')) {
      cp.execSync('git rev-parse HEAD > git-commit-hash')
    }
    const gitCommitHash = fs.readFileSync('git-commit-hash', { encoding: 'utf-8' })

    return gitCommitHash
  },
}
```

and added a `precommit` hook that would write my last git commit hash to a file. The file would be referenced by `next.config.js` to generate a consistent build id.

```json
// package.json
{
  "engines": {
    "node": "^8.4.0"
  },
  "scripts": {
    "precommit": "git rev-parse HEAD > git-commit-hash && git add git-commit-hash",
  },
  "dependencies": {
    "next": "^6.0.3",
  },
  "devDependencies": {
    "husky": "^0.14.3",
  }
}

```

**Comment by makinde** [comment]
If anyone comes across this. Looks like Heroku provides the git hash in an env variable. Details here: https://devcenter.heroku.com/changelog-items/630 . So I stopped using the module and just did:
```js
{
  generateBuildId() {
    if (process.env.SOURCE_VERSION) {
      return `cust-next-build-${process.env.SOURCE_VERSION}`;
    }
    return null;
  },
}
```
...in my next.config.js

**Comment by brennanerbz** [comment]
Any progress on this? Can't seem to get it working for Google Cloud.

**Comment by brennanerbz** [comment]
Related: https://github.com/zeit/next.js/issues/11094

**Comment by nexdrew** [comment]
@brennanerbz I'm not too familiar with App Engine, but if you're using Cloud Builder to build your Next.js app, you might want to try one of these environment variables provided out-of-the-box: https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values

Something like what [Makinde posted above](https://github.com/nexdrew/next-build-id/issues/9#issuecomment-515775375) except use `process.env.COMMIT_SHA` or `process.env.SHORT_SHA` or `process.env.TAG_NAME`.
